import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "./components/ui/navbar/Navbar";

export const metadata: Metadata = {
  title: "Pokemon App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={"dark"}>
      <body>
        <Navbar />
        <div className="p-6">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
